- name: Install and start Elasticsearch
  hosts: elasticsearch
  become: true
  tasks:
    - name: Update environment variables
      shell: sysctl -w vm.max_map_count=262144 

    - name: Start an Elastic search container
      docker_container:
        name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        state: started
        ports:
            - "9200:9200"
            - "9300:9300"
        env:
          discovery.type: single-node