- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker and pip
      shell: |
        set -e
        apt-get update
        apt-get -y install software-properties-common python3-pip
        curl https://get.docker.com/ | bash

    - name: Install docker-py
      pip:
        name: docker-py
  